### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by maksim-luzin** [maksim-luzin/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by maksim-luzin** [comment]
### **DONALD TRUMP**
_________________________________________________________________________________________________________

My contacts:
- [Facebook](https://www.fb.com/DonaldTrump) 

- [Instagram](https://www.instagram.com/realDonaldTrump/)

- [twitter](https://twitter.com/realDonaldTrump)

- [mail](realDonaldTrump@whitehouse.gov)

**Comment by maxim-collaborator** [comment]
Well, you can close Issue.

**Comment by maksim-luzin** [comment]
Ok.
