### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by maksim-luzin** [maksim-luzin/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by maxim-collaborator** [comment]
[facebook](https://www.fb.com/DonaldTrump)
[mail](realDonaldTrump@whitehouse.gov)
[twitter](https://twitter.com/realDonaldTrump)
[instagram](https://www.instagram.com/realDonaldTrump/)

**Comment by maksim-luzin** [comment]
Thank you.
